version: "3.9"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_URI: ${DB_URI}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
